def configure(conf):
    conf.check_cxx(fragment="""
                            #define BOOST_TEST_MODULE Config test\n
    			    #include <boost/test/unit_test.hpp>\n
                            int main() {}
                            """,
                            msg='Checking for boost unit testing library',
                            lib='boost_unit_test_framework',
                            uselib_store='BOOST_TEST')

    conf.env.prepend_value('LINKFLAGS', '-Lsrc')

def build(bld):
    obj = bld(features='cxx cxxprogram')
    obj.name   = 'tests'
    obj.uselib = 'BOOST_TEST CXML'
    obj.use    = 'libsub'
    obj.source = """
                 dcp_reader_test.cc
                 dcp_to_stl_binary_test.cc
                 iso6937_test.cc
                 stl_binary_reader_test.cc
                 stl_binary_writer_test.cc
                 stl_text_reader_test.cc
                 time_test.cc
                 test.cc
                 """
    obj.target = 'tests'
    obj.install_path = ''
