/*
    Copyright (C) 2014 Carl Hetherington <cth@carlh.net>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

*/

/* THIS FILE WAS AUTO-GENERATED BY iso6937.py */

#include <map>

namespace sub {

extern void make_iso6937_tables ();

namespace iso6937 {

extern std::map<char, wchar_t> main;
extern std::map<char, std::map<char, wchar_t> *> diacriticals;
extern std::map<char, wchar_t> grave;
extern std::map<char, wchar_t> acute;
extern std::map<char, wchar_t> circumflex;
extern std::map<char, wchar_t> tilde;
extern std::map<char, wchar_t> macron;
extern std::map<char, wchar_t> breve;
extern std::map<char, wchar_t> dot;
extern std::map<char, wchar_t> diaeresis;
extern std::map<char, wchar_t> ring;
extern std::map<char, wchar_t> cedilla;
extern std::map<char, wchar_t> double_acute;
extern std::map<char, wchar_t> ogonek;
extern std::map<char, wchar_t> caron;

}
}
