from waflib import TaskGen

def build(bld):
    if bld.env.STATIC:
        obj = bld(features='cxx cxxstlib')
    else:
        obj = bld(features='cxx cxxshlib')

    obj.name = 'libsub-1.0'
    obj.target = 'sub-1.0'
    obj.uselib = 'CXML DCP BOOST_FILESYSTEM BOOST_LOCALE'
    obj.export_includes = ['.']
    obj.source = """
                 colour.cc
                 dcp_reader.cc
                 effect.cc
                 font_size.cc
                 frame_time.cc
                 iso6937.cc
                 iso6937_tables.cc
                 metric_time.cc
                 raw_subtitle.cc
                 reader.cc
                 reader_factory.cc
                 stl_binary_reader.cc
                 stl_binary_tables.cc
                 stl_binary_writer.cc
                 stl_text_reader.cc
                 stl_util.cc
                 time_pair.cc
                 subrip_reader.cc
                 subtitle.cc
                 vertical_reference.cc
                 vertical_position.cc
                 """

    headers = """
              collect.h
              colour.h
              dcp_reader.h
              effect.h
              font_size.h
              frame_time.h
              metric_time.h
              raw_subtitle.h
              reader.h
              stl_binary_tables.h
              stl_binary_writer.h
              stl_text_reader.h
              subrip_reader.h
              subtitle.h
              time_pair.h
              vertical_position.h
              vertical_reference.h
              """

    bld.install_files('${PREFIX}/include/libsub-1.0', headers)
    if bld.env.STATIC:
        bld.install_files('${PREFIX}/lib', 'libsub-1.0.a')
